package ricochetrobots;

import java.awt.Color;
import java.util.List;
import static ricochetrobots.RicochetUtil.*;

/**
 *
 * @author Philipp
 */
public class JFrame extends javax.swing.JFrame {

    private final String[] botTexts = new String[NUM_BOTS];
    private final String[] directionTexts = new String[NUM_DIRECTIONS];
    private final Color[] colors = new Color[NUM_BOTS];

    private final int red = 0;
    private final int blue = 1;
    private final int yellow = 2;
    private final int green = 3;
    private final int silver = 4;

    {
        botTexts[red] = "red ";
        botTexts[blue] = "blue ";
        botTexts[yellow] = "yellow ";
        botTexts[green] = "green ";
        botTexts[silver] = "silver ";

        directionTexts[UP] = "up";
        directionTexts[LEFT] = "left";
        directionTexts[DOWN] = "down";
        directionTexts[RIGHT] = "right";

        colors[red] = Color.RED;
        colors[blue] = Color.BLUE;
        colors[yellow] = Color.YELLOW;
        colors[green] = Color.GREEN;
        colors[silver] = Color.GRAY;
    }

    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();

        RicochetState state = new BitmaskRicochetState();

        int targetBot = blue;
        int targetSquare = setup5bots22movesForBlue(state);

        new Thread(() -> {
            RicochetSolver solver = new RicochetSolver(state, new TranspositionTable(26));//26 -> 1 GB
            List<Integer> solve = solver.solve(targetBot, targetSquare);
            for (int i = 0; i < solve.size(); i += 2) {
                System.out.println(botTexts[solve.get(i)] + directionTexts[solve.get(i + 1)]);
            }
            System.exit(0);
        }).start();

        BoardPanel panel = new BoardPanel(state, colors);
        panel.target = targetSquare;
        panel.targetColor = colors[targetBot];
        panel.setSize(500, 500);
        add(panel);
        panel.invalidate();
    }

    private int setup5bots22movesForBlue(RicochetState state) {
        state.addBot(red, square(2, 14));
        state.addBot(blue, square(11, 2));
        state.addBot(yellow, square(2, 1));
        state.addBot(green, square(0, 3));
        state.addBot(silver, square(2, 2));

        state.setWall(square(4, 0), RIGHT);
        state.setWall(square(9, 0), RIGHT);
        state.setWall(square(14, 0), UP);
        state.setWall(square(2, 1), UP);
        state.setWall(square(2, 1), RIGHT);
        state.setWall(square(13, 1), RIGHT);
        state.setWall(square(10, 2), RIGHT);
        state.setWall(square(11, 2), UP);
        state.setWall(square(0, 3), RIGHT);
        state.setWall(square(1, 3), UP);
        state.setWall(square(15, 3), UP);
        state.setWall(square(0, 4), UP);
        state.setWall(square(5, 4), RIGHT);
        state.setWall(square(5, 5), UP);

        state.setWall(square(5, 6), RIGHT);
        state.setWall(square(7, 6), UP);
        state.setWall(square(8, 6), UP);
        state.setWall(square(10, 6), UP);
        state.setWall(square(13, 6), UP);
        state.setWall(square(13, 6), RIGHT);
        state.setWall(square(3, 7), UP);
        state.setWall(square(3, 7), RIGHT);
        state.setWall(square(6, 7), RIGHT);
        state.setWall(square(8, 7), RIGHT);
        state.setWall(square(10, 7), RIGHT);
        state.setWall(square(6, 3), UP);

        state.setWall(square(7, 8), LEFT);
        state.setWall(square(7, 8), UP);
        state.setWall(square(8, 8), RIGHT);
        state.setWall(square(8, 8), UP);
        state.setWall(square(3, 9), DOWN);
        state.setWall(square(3, 9), RIGHT);
        state.setWall(square(14, 9), LEFT);
        state.setWall(square(14, 9), DOWN);
        state.setWall(square(11, 10), UP);
        state.setWall(square(11, 10), LEFT);
        state.setWall(square(1, 11), UP);
        state.setWall(square(1, 11), LEFT);

        state.setWall(square(2, 14), LEFT);
        state.setWall(square(2, 14), DOWN);
        state.setWall(square(0, 14), DOWN);
        state.setWall(square(6, 15), LEFT);
        state.setWall(square(11, 15), RIGHT);
        state.setWall(square(13, 14), UP);
        state.setWall(square(13, 14), RIGHT);
        state.setWall(square(9, 12), RIGHT);
        state.setWall(square(9, 12), DOWN);
        state.setWall(square(15, 10), UP);
        state.setWall(square(6, 12), UP);
        state.setWall(square(6, 12), RIGHT);

        return square(9, 12);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
